name: "Docs Gen"
on:
    push:
      branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install pydata_sphinx_theme sklearn scipy numpy matplotlib
    - name: Build the docs
      run: |
        cd TD4/docs && sphinx-build -b singlehtml . _build && ls -alh _build
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: TD4/docs/_build/
